### ISSUE TITLE
TV is not asking for authorization

### ISSUE THREAD

**Issue by adeeltahir98** [Ape/samsungctl#118]
I am trying to connect to samsung tv using websockets but I am getting no authorization dialogue on tv and consequently getting this in error response:

samsungctl.exceptions.UnhandledResponse: {'event': 'ms.channel.unauthorized'}

On the other hand If I try to connect using legacy then I get this error:

b'P/1.0 403 Forbidden\r\ncontent-type: text/html\r\ncontent-length: 38\r\n\r\n<html><body><h1>403</h1></body><'
samsungctl.exceptions.UnhandledResponse: b'tml>'

Please anyone tell me what I am doing wrong. Thanks

**Comment by gbrissey** [comment]
Look at the QSeries issue discusses this issue for the Q series TVs

**Comment by adeeltahir98** [comment]
Thank you. That works !!
