### ISSUE TITLE
Netflix app

### ISSUE THREAD

**Issue by Rago11** [Ape/samsungctl#131]
Hi guys, everything is working fine except Netflix app. I really dont know why is that. I have tried all 3 options for app_list but none of them works. HBO, Youtubey Spotife - those are working fine when i click them on source it switches to them. Netflix? NOPE... When I change it manually with my remote then it refreshes its status on HA also to netflix, but when I change it in HA from something to netflix it just does nothing at all. As I run out of options help is appreciated. Thank you. 

Do you have any idea why ? 

That is my applist config. 

app_list: '{"YouTube": "111299001912", "Netflix": "11101200001/org.tizen.netflix-app", "Spotify": "3201606009684", "HBO GO": "3201706012478"}'

**Comment by tavicu** [comment]
if you have a newer TV the ID for Netflix is `3201907018807`

**Comment by Rago11** [comment]
Thank you very much... It works now
