### ISSUE TITLE
Samsung KS8000 support?

### ISSUE THREAD

**Issue by nunofgs** [Ape/samsungctl#18]
Hello, I have a KS8000 Samsung TV and have found that port 55000 is not open. Any ideas on how we could support my TV?

Here's a quick nmap of the running TV:

```
Host is up (0.010s latency).
Not shown: 994 closed ports
PORT     STATE SERVICE
7676/tcp open  imqbrokerd
8000/tcp open  http-alt
8001/tcp open  vcom-tunnel
8002/tcp open  teradataordbms
8080/tcp open  http-proxy
9999/tcp open  abyss
```

**Comment by kylerw** [comment]
Same question here!

**Comment by Ape** [comment]
Try to run samsungctl on those ports and see if any of them work. But I think it's likely that KS8000 doesn't support the same remote control interface.

**Comment by nunofgs** [comment]
@kyleaa has gotten this to work on his [homebridge-samsungtv2016](https://github.com/kyleaa/homebridge-samsungtv2016) homebridge plugin. I've successfully tested this on my tv and it works great!

@Ape any chance you could add support for this on _samsungctl_?

**Comment by Ape** [comment]
@nunofgs Thanks for the information. It seems that the control interface is very similar to the old one implemented in samsungctl. The difference is just that the new protocol uses websockets and json. It would be quite easy to provide an alternative implementation for `samsungctl/remote.py`.

I don't have the new kind of TV so I don't have the necessary motivation to implement this myself. However, I would gladly accept pull requests for this feature.
