### ISSUE TITLE
no response from TV

### ISSUE THREAD

**Issue by jonny190** [Ape/samsungctl#36]
Hi, when using this commad: 

samsungctl --host 192.168.5.91 --port 8001 KEY_MUTE --method websocket --name "home-assistant" --id 1234567890 --timeout 30 -v

the output is : Sending control command: KEY_MUTE

the TV dosent ask me to accept it as a remote, any ideas?

**Comment by Levynger** [comment]
Having the same issue with my 48UE6300.. 
no control, no errors, and no request for to accept the connection on the TV..

**Comment by nspinelli** [comment]
not working on UN60JS6900.

**Comment by Ape** [comment]
Please see #22.
