### ISSUE TITLE
How to get acknowledgement from samsung Tv ?

### ISSUE THREAD

**Issue by Gowtham1989** [Ape/samsungctl#39]
Hi,
I have sent "KEY_POWEROFF" command to samsung smart tv. The TV is turn off successfully. 
But, i want to get acknowledgement from TV. how to get acknowledgement from TV?
For example, If i am changing my channel every time it should acknowledge to me.

**Comment by Ape** [comment]
You should be getting some error message in case the TV didn't receive the command. This would be an exception if you are using the Python library or command line output with the command line tool. So if you didn't get any error, then the TV most likely received your command. Is this enough for you?

**Comment by Gowtham1989** [comment]
Thank you @Ape , That is enough. I have one more question. How can i open the applications present in the TV?? For example, assume there are wiki app,bbc news app,web browser app etc.. Now, i want to open bbc news app, how to open it, which commands i have to pass??

**Comment by Ape** [comment]
1. I do not know any direct way to do that. You may try to combine multiple key presses on the remote.

2. This seems to vary between TV models, but you can try if setting `--id` to some value helps.
