### ISSUE TITLE
How to set volume to specific value

### ISSUE THREAD

**Issue by Gowtham1989** [Ape/samsungctl#41]
Hi friends,
      I want to set my TV volume to specific value like "Volume 40, Volume 55". How can we set like, how we are setting for channels.

**Comment by Ape** [comment]
This might not be supported by the TV. I don't know if the later APIs have this feature.

**Comment by eclair4151** [comment]
i looked through all the commands from the Smart_View app. even the app doesn't support setting volume to a specific volume. i think this feature is just unsupported by the Tvs

**Comment by Ape** [comment]
Let's close this until somebody finds a way to implement this (if ever).
