### ISSUE TITLE
how to operate Multiple key?

### ISSUE THREAD

**Issue by Gowtham1989** [Ape/samsungctl#45]
Hi,
I want to operate multiple keys (KEY_0,KEY_1,KEY_2......,) in python program.  
Where those keys are mainly used ?. I'm trying those keys to open applications present on the TV. how can i achieve this?

**Comment by Ape** [comment]
What do you mean operate the keys? Do you want to send multiple key presses in a sequence?

**Comment by Gowtham1989** [comment]
Yes

**Comment by Ape** [comment]
You can call `control` multiple times:

```python
with samsungctl.Remote(config) as remote:
    remote.control("KEY_0")
    remote.control("KEY_1")
    remote.control("KEY_2")
```

You should probably add some sleeps between the calls because the TV cannot usually handle presses too quickly. But this depends on the model and which key presses you are using.

**Comment by Gowtham1989** [comment]
OK. Thank you.
