### ISSUE TITLE
Authentication on TV each time i user samsumgctl

### ISSUE THREAD

**Issue by zechasso** [Ape/samsungctl#48]
Hi there,
I get the authentication message on TV each time I use samsungctl.
I have to agree it, afterwards the sent key-command is executed.
Can you tell how to solve this problem please?

**Comment by Ape** [comment]
#16 might be related.

**Comment by YuriGuzun** [comment]
Try to pass same --id value

**Comment by peterberbec** [comment]
@zechasso - I had the same problem. YuriGuzun's solution worked perfectly for me. I just picked a number and stuck to it, works great now.

**Comment by Ape** [comment]
Duplicate of #16.
