### ISSUE TITLE
Porting to C#

### ISSUE THREAD

**Issue by bjm2020** [Ape/samsungctl#49]
Hi,

I'm attempting to port this over to c# to eventually use in homeseer for my 2016 UN55KU6270.

I'm able to get a connection and authenticate with the tv.  However, after sending the JSON I'm getting the following error from the tv:

`{"event":"ms.error","data":{"message":"missing method field from message"}}`

I'm sending the following JSON across:

`"{\"method\":\"ms.remote.control\",\"params\":\"{\"Cmd\":\"Click\",\"DataOfCmd\":\"KEY_MENU\",\"Option\":\"false\",\"TypeOfRemote\":\"SendRemoteKey\"}\"}"`

Any clue what I'm doing wrong here?

**Comment by Ape** [comment]
You can try to repeat the same messages samsungctl is sending. Make sure you have everything exactly the same.

I'm closing this issue since it doesn't really belong to this project.
