### ISSUE TITLE
Unexpected behavior for KEY_HDMI

### ISSUE THREAD

**Issue by mikegagnon** [Ape/samsungctl#50]
@nunofgs @Ape First, samsungctl has been working great for me with my Samsung UN24M4500AF. So, this isn't really a question about the samsungctl project. Rather, it's a question regarding my Samsung TV. KEY_HDMI and KEY_HDMI1 etc. do not switch to the specified HDMI. Instead, KEY_HDMI cycles through the input sources. Do you know if this functionality is common among many Samsung TVs, or does it only apply to few Samsung TVs?

Thank you!

**Comment by Ape** [comment]
There are some differences between the TV models. Sometimes the key codes are named weirdly. It would be useful if we could document all the model specific key codes somehow.

**Comment by mikegagnon** [comment]
Thank you.

**Comment by Ape** [comment]
Closing. This is mostly expected behaviour.

**Comment by SimpsonTellis** [comment]
@Ape, @nunofgs do you have any idea about where will we get the KEY_CODEs for different models.
In TV manuals or anywhere documented or in any code.
