### ISSUE TITLE
Key code for smart hub

### ISSUE THREAD

**Issue by lervag** [Ape/samsungctl#54]
I'm trying to use samsungctl to automate some common tasks. However, most tasks relevant to me involves the smart hub, and I can't find or figure out the key code for that. Does anyone know it, or is anyone able to figure it out by sniffing the network traffic?

**Comment by pedrinho** [comment]
@lervag on my tv UN40F5500 is KEY_CONTENTS

**Comment by lervag** [comment]
Thanks! That's it! :)

**Comment by lervag** [comment]
Ah, I guess because it's considered an answered question. However, I would think it makes sense to add this key to the list of interactive commands?

**Comment by Ape** [comment]
Hmm, you are right. Can you submit a PR?

**Comment by lervag** [comment]
@pedrinho was faster than me. In any case, I think it is better to continue the discussion at #65.
