### ISSUE TITLE
Power ON UA55M5500

### ISSUE THREAD

**Issue by rifqimr** [Ape/samsungctl#82]
Can i power on that TV using this library ?
Or, how i can know that TV support wake-on-lan ?

**Comment by nickyromeijn** [comment]
I don't think it's possible to turn on your TV with this lib. I turn my TV on (KS8000) with a wake on lan (WOL) packet. See https://www.cyberciti.biz/tips/linux-send-wake-on-lan-wol-magic-packets.html for example

**Comment by rifqimr** [comment]
hey bro @nickyromeijn , thanks for your link ! Great ! now i can wake up / powering on my TV using tutorial from your link ! big thanks 😄
